name: viam_flutter_bluetooth_provisioning_widget
description: "A Flutter package for provisioning Viam machines using Bluetooth connections with support for both standard provisioning and tethering flows."
repository: https://github.com/viamrobotics/viam_flutter_bluetooth_provisioning_widget
version: 0.0.28
homepage: https://www.viam.com

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.0+1
  viam_sdk: ">=0.10.0 <=0.13.1"
  collection: ^1.18.0
  viam_flutter_provisioning: ^0.0.16
  flutter_platform_widgets: ^7.0.1
  provider: ^6.1.5
  pub_semver: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <7.0.0"
  mockito: ^5.4.6
  build_runner: ^2.4.13

flutter:
  assets:
    - lib/src/assets/
